name: flutter_bluetooth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  flutter_triple: ^1.2.6
  flutter_reactive_ble: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  triple_test: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true